[tool.bumpversion]
current_version = "0.0.9"
parse = "(?P<major>\\d+)\\.(?P<minor>\\d+)\\.(?P<patch>\\d+)"
serialize = ["{major}.{minor}.{patch}"]
search = "{current_version}"
replace = "{new_version}"
regex = false
ignore_missing_version = false
ignore_missing_files = false
tag = false
sign_tags = false
tag_name = "v{new_version}"
tag_message = "Bump version: {current_version} → {new_version}"
allow_dirty = true
commit = false
message = "Bump version: {current_version} → {new_version}"
moveable_tags = []
commit_args = "n"
setup_hooks = []
pre_commit_hooks = []
post_commit_hooks = []


[[tool.bumpversion.files]]
filename = "./pyproject.toml"
search  = "version = \"{current_version}\""
replace = "version = \"{new_version}\""

[[tool.bumpversion.files]]
filename = "./schema/yaml_template_schema.json"
search  = "\"default\": \"{current_version}\""
replace = "\"default\": \"{new_version}\""

[[tool.bumpversion.files]]
filename = "./appm/__version__.py"
search  = "__version__ = \"{current_version}\""
replace = "__version__ = \"{new_version}\""

[[tool.bumpversion.files]]
filename = "./appm/default.py"
search  = "\"version\": \"{current_version}\""
replace = "\"version\": \"{new_version}\""


